language: node_js
node_js:
  - "4.2"
cache:
  directories:
    - node_modules
script: npm run build
after_success:
  - eval "$(ssh-agent -s)"
  - >
      openssl aes-256-cbc
      -K $encrypted_b706d7a8956c_key
      -iv $encrypted_b706d7a8956c_iv
      -in id_rsa.enc -out id_rsa -d
  - cat frontend-union.host > ~/.ssh/known_hosts
  - chmod 600 id_rsa
  - ssh-add id_rsa
  - rsync -av "build/" "func@andreysalomatin.me:func2016"


